### PR TITLE
Windows/return message embed

### PR DESCRIPTION
**Pull request by mdlugosz1**
- [x] You have read the [Odin Bot README/Contributing Guide](https://github.com/TheOdinProject/odin-bot-v2/blob/master/README.md).

#### 1.Describe the changes made:

Updated /windows command to return MessageEmbed with title, color, description and link. Command snapshot was also updated.

#### 2. If this PR modifies a command, please provide a screenshot of the passing tests below. NOTE: Your PR will not be merged if you have any failing test cases. 

test

discordcommand

#### 3. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#148

### CODE REVIEW

**Comment by twalton83** [comment]
One small favor- please set the color of the embed. You can take the color and code from the new faq embed!

**Comment by twalton83** [comment]
On second thought though, let’s also keep the link to the lesson in the description so it’s more obvious.

**Comment by mdlugosz1** [comment]
Here is screenshot of how command will look after changes

discordcommand

**Review by twalton83 — APPROVED** [review]
Thank you!

**Pull request merged**
