### PR TITLE
Add /points slash command to explain the points system in our server

### PR DESCRIPTION
**Pull request by ManonLef**
## Because

Users often ask what the points system is for, this command will explain the following:
- Why we give points
- How we give points
- How not to use points

Screenshot 2023-07-31 at 00 57 48

## This PR

- adds a `/points` slash command with an output as shown above

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update verbiage`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If this PR adds new features or functionality, I have added new tests
-   [ ] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date

### CODE REVIEW

**Comment by Mclilzee** [comment]
This has potential conflict with the already existing command `!points`, which is broken atm and I had an issue to fix it #356. One solution is I could change the `!points` command to `!rank`. I didn't want to put a PR before I get assigned the issue.

**Comment by ManonLef** [comment]
@Mclilzee Thanks for mentioning this! It shouldn't have for this is a slash command and the other one is the old style exclamation command. 

I do like the idea of renaming it to rank for the `!` command if that issue gets reviewed and opened for PR. But we can also consider renaming this one if needed, which is a small change :)

**Comment by Mclilzee** [comment]
@ManonLef This one being `/points` makes perfect sense, I don't think you should change the name. `!rank` is more clear what the other command will be doing, which is to fetch someone's rank in the leaderboard and show which place they are in, showing the point in the same msg is just extra.

It is true that `/points` and `!points` will be treated as different commands, but i think for clarity sake its best that we keep this explanation as `/points` and the other one as `!rank`.

Great work on the embed! this embed looks awesome.

**Review by codyloyd — APPROVED** [review]
nice work.. approved.

merge when ready.

**Pull request merged**
