### PR TITLE
points and rotation commands: Escape markdown in display names

### LINKED ISSUE #571: Bug - points command: Symbols aren't escaped
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - points command: Extra whitespace causes command to not be called`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

When people have special/punctuation characters in their names it causes unexpected side effects because of Discord's message formatting. For example I added "\`test\`" into my name and that caused the points command to show my name as "name `test`" instead of "name \`test\`". 

That can happen with other symbols as well(the 2 examples are shown in the screenshots below). The second example shows that adding \|\| into ones name triggers the spoiler format(if there is another set of \|\| after) which hides lines of the message in between the vertical lines.

image
image
image
image

**2. How To Reproduce:**

1. Use the points command
2. Find a name where there is Discord formatting or rename your server name to include Discord formatting

**3. Expected Behavior:**

1. Use the points command
2. You see your name with the characters not formatted, instead they are escaped

**4. Desktop/Device:**

-   Device: Laptop and mobile so far(probably a problem on all devices)
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

### PR DESCRIPTION
**Pull request by T0nci**
## Because

When users had markdown in their username/nickname(display name) and the bot printed the user's display name in some commands, the markdown wasn't escaped and it caused unwanted formatting in the bot's reply.

## This PR

- Integrates `escapeMarkdown` wherever a display name is mentioned in the points command
- Integrates `escapeMarkdown` wherever a username/nickname is mentioned in the rotation command
- Updates the tests for both commands to test if markdown is escaped in display names

## Issue

Closes #571

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update verbiage`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If this PR adds new features or functionality, I have added new tests
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date

### CODE REVIEW

**Review by MaoShizhong — CHANGES_REQUESTED** [review]
This looks awesome and seems to work just fine on my machine. You will need Redis active to test the rotations locally.

Could you run Prettier on all of the changed files (except the snapshots of course)? We have a `format` npm script where you can pass in the file path(s) to format (e.g. `npm run format -- "./services/rotations/rotation.service.js"`).

Edit: Nit - in your rotation service tests, you shouldn't need a separate `additionUsers` variable if you just call `getUsers(2)` in the first place (since that'll return an array of the first 2 users - no need to slice afterwards given you don't use the 3rd user onwards).

**Comment by T0nci** [comment]
Sadly I tried installing Redis through the CLI(with 2 methods on their site) and both times my VM wouldn't start up. So I had to remove it. Thanks for testing the rotation commands locally!

Yes of course! I was searching for the `markdown-lint` package and couldn't find it.

In what line is that? I can't seem to find it. I call `getUsers` in every test without a number, so I get all users from the function.

**Comment by MaoShizhong** [comment]
> In what line is that? I can't seem to find it. I call getUsers in every test without a number, so I get all users from the function.

In all of your new tests for the rotation service, you call `getUsers()` without any args which will return the whole users array which you then slice out the first two elements. If you call `getUsers(2)` then it'll return the first two sliced out already, so no need to slice again.

**Comment by T0nci** [comment]
Oh I see. I was calling `getUsers` without args to get more users to simulate a more "real" test server(which doesn't make sense :/) and now I see that all that extra mock data is unnecessary. I will update the tests.

OH I only got it now lol, MARKDOWNlint for MARKDOWN files xD

**Review by MaoShizhong — APPROVED** [review]
:rocket: Amazing work with this one!

**Pull request merged**
