### PR TITLE
/faq - remove quote, update title, update link to channel id

### PR DESCRIPTION
**Pull request by JustWaveThings**
## Because

- Improves `/faq` command's tone

## This PR

- Change title to 'TOP FAQ'
- Remove quote about insanity
- Updated link to FAQ channel to use channel Id 

## Issue

N/A

## Additional Information

- https://discord.com/channels/505093832157691914/897162466226757692/1215373112032628736

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update verbiage`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If this PR adds new features or functionality, I have added new tests
-   [ ] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date

### CODE REVIEW

**Comment by JustWaveThings** [comment]
- Oh no, I forgot to turn that format on save thing off.  I can do that.
- I'll update the template to string

**Comment by JustWaveThings** [comment]
Oh wait, there's still the single quote / doublequote issue. One moment.

**Comment by JustWaveThings** [comment]
Ok, now the diff looks normal.  Thanks @MaoShizhong!  I've saved this setup as a vscode profile so hopefully, it won't be an issue going forward.

**Review by MaoShizhong — APPROVED** [review]

**Comment by MaoShizhong** [comment]
Easy error! I just have formatting bound to a kb shortcut and just don't hit that shortcut in the repos XD
That being said, `prettier` is installed as a dependency (also why is it a dep and not a devdep?) but we don't have a `.prettierrc` ruleset.
Might open an issue to get one added with the closest rules to what the current formatting is like. Then that'd help reduce these sorts of things.

**Pull request merged**
