### PR TITLE
/help command - Add user ping option and overhaul embed content

### PR DESCRIPTION
**Pull request by JustWaveThings**
## Because

- Because the previous /help command was duplicated with a /points command

## This PR

- Add an optional ability to tag a user
- Update the title from "help" to "Get help on The Odin Project's Discord Server"
- Numerous body content changes. See Screenshot:
image

## Issue

Related to #422 

## Additional Information

- I did not write any tests. I didn't see any snapshots for the other slash commands. I did visually inspect the output on macOS and iOS Discord clients.

- https://discord.com/channels/505093832157691914/1154146232063770747

-  ~~This command mentions the `/windows` command so it needs to be on the list to update when WSL2 support is announced.~~ removed 

- I explored but did not implement the structure to have multiple sub-commands in this PR. I chose to submit this and hopefully get it approved and replace the current `/help` command, and from there, work with the team on an overall strategy for which sub-commands to include. I do think that the body content in this command would work as an 'info' subcommand, much like the one for the '/points info' subcommand. 

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update verbiage`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If this PR adds new features or functionality, I have added new tests
-   [ ] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date

### CODE REVIEW

**Comment by Mclilzee** [comment]
This looks good!

Feedback: I feel it have one too many Thank yous. I feel it would be better to move the `contribution` and `support` commands and mention them at the footer, they will blend nicely since the footer talks about contribution and supporting

**Comment by JustWaveThings** [comment]
Good feedback!  I merged the two fields and put them at the bottom. I think it definitely looks better than the first version.

image

**Comment by JustWaveThings** [comment]
Okay, I think this might be closer to what we are looking for in a general /help command (or eventually /help info subcommand). What do we think?  

image

**Comment by JustWaveThings** [comment]
I've been thinking about this. I think there are some improvements I can make that would make it better.

**Comment by JustWaveThings** [comment]
I moved some stuff around and made some other changes.   

Let me know what you think.

image

**Comment by 01zulfi** [comment]
@JustWaveThings any updates on this?

**Comment by JustWaveThings** [comment]
Yep, let me get to the computer and I'll push the changes! Sorry just thought I had.

**Comment by JustWaveThings** [comment]
Hey @01zulfi, what's the trick for using channel id's vs links to channels in the embeds? I thought I had already done that but I had not.  I can't find your message with the trick.

**Comment by JustWaveThings** [comment]
This is what it looks like now. 

icurrent bot command

**Review by 01zulfi — APPROVED** [review]

**Pull request merged**
