### PR TITLE
Update /code to include syntax highlighting

### PR DESCRIPTION
**Pull request by zachmmeyer**
It'd be nice to see some colors and better information.

### CODE REVIEW

**Comment by I3uckwheat** [comment]
Oh nice, thanks @zachmmeyer, we'll merge this after the testing stuff is implemented fully :)

**Comment by twalton83** [comment]
Can we revisit this now that they've been merged? @zachmmeyer, are you willing to do the tests for this?

**Comment by zachmmeyer** [comment]
I'm willing to do the tests, I just don't know how to do them.

**Comment by twalton83** [comment]
We have a new README that has been merged to master and should have all the instructions! As a heads up though, you'll need to `npm i` the new dependencies, and when you run the tests only run `npm test commandName.test.js` instead of `npm test` as the README currently describes. Waiting on some PRs to update those pieces to be merged.

**Comment by zachmmeyer** [comment]
Understood. I will go check out the README and look at the instructions. Thank you @twalton83 !!!

**Comment by twalton83** [comment]
Were you still interested in knocking this out?

**Comment by zachmmeyer** [comment]
Oh wow I completely forgot about this.

I'm going to say no!

I'll read the read me at another time, if you all don't think this is something necessary for the bot, might as well kill it. Or if someone else is willing to do the testing.

**Review by I3uckwheat — CHANGES_REQUESTED** [review]
wtf

**Comment by I3uckwheat** [comment]
I wanted to close it

**Pull request closed without merging**
