### PR TITLE
/support: Fix: Update Emoji (#431)

### PR DESCRIPTION
**Pull request by ItsTosh**
Updated donate emoji to '1270559118368964710' to be more 'open'

## Because
- Money bag emoji could be associated with 'greed' therefore the emoji was changed to the backer coin emoji to be more "open" 

## This PR
- Updated money bag emoji to backer coin emoji.
- Updated `.setEmoji('💰');` to `.setEmoji('1270559118368964710')`.

## Issue

Closes https://github.com/TheOdinProject/odin-bot-v2/issues/431 

## Additional Information

- N/A

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update verbiage`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If this PR adds new features or functionality, I have added new tests
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date

### CODE REVIEW

**Review by MaoShizhong — COMMENTED** [review]
Many thanks @ItsTosh! Would you mind running the following command in the root of your bot repo?
```bash
npm run format -- new-era-commands/slash/support.js 
```
That should format the file according to our Prettier rules in preparation for #576

**Comment by ItsTosh** [comment]
@MaoShizhong Hey Mao! Not sure if I did this correctly, but I ran `npm install` on my repo and then the command you gave me. Is this the expected output:

```
// Command
$ npm install
$ npm run format -- new-era-commands/slash/support.js 

// Output
> bot-v2@1.0.0 format
> prettier --cache --write new-era-commands/slash/support.js

new-era-commands/slash/support.js 51ms
```

Is this alright? Can I commit and push again?

**Comment by Asartea** [comment]
Looks good to me

**Comment by MaoShizhong** [comment]
Looks right to me.

**Pull request merged**
