### PR TITLE
botCommands: Add !memory command

### PR DESCRIPTION
**Pull request by JakeBrowning90**
## Because

This PR adds a function to the odin-bot to provide a link to Carlos' blog post on memorization, and allows users to refer question-askers seeking advice on how to memorize the learning material.

## This PR

-Registers a "!memory" bot command.
 -Adds a test suite derived from the format provided in the wiki.

## Issue

Closes #XXXXX

## Additional Information

Original post with link to blog post: https://discord.com/channels/505093832157691914/564517555629457428/1146483003019767828

Recommendation to contribute a bot command as experience: https://discord.com/channels/505093832157691914/514204569572605952/1146604613315870760

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update verbiage`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If this PR adds new features or functionality, I have added new tests
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date

### CODE REVIEW

**Review by 01zulfi — CHANGES_REQUESTED** [review]
Hello @JakeBrowning90, thanks for wanting to contribute!

I think memory card would be a great addition. Though we're moving away from text-based commands in favour of slash commands. More info here https://github.com/TheOdinProject/odin-bot-v2/issues/297

Would you be willing to create a memory slash command?

**Comment by ManonLef** [comment]
I also love it! On top of what @01zulfi mentioned;

- I’d prefer our embed format since it makes the bot messages stand out better
- I’ve also started making the links descriptive/hyperlinks. It shortens the message and makes it look cleaner and more in line with the accessibility we go for throughout the curriculum even though I’m not sure yet how discord handles these.

**Comment by JakeBrowning90** [comment]
Thank you for the feedback. I can absolutely incorporate the recommended changes, though I'll need to spend some time figuring out the details. I'll update as soon as I can.

**Comment by 01zulfi** [comment]
@JakeBrowning90 Take your time. If you any questions/suggestions, let me know

**Comment by JakeBrowning90** [comment]
@01zulfi  Pardon, 2 things I need clarification on:
1. When I submit my PR for the slash-command, should I also remove the text-command from my first PR?
2. Is there a testing requirement for slash-commands? I haven't spotted a snapshot folder or anything <command>.test.js files in the new-era-commands folder.

**Comment by 01zulfi** [comment]
1. If you're making a new PR, make sure you checkout from the latest `main` branch of this repo. Then you'll have no need to remove commits from this PR.
2. Setting up testing requirements for slash commands is still in progress. You don't have to add tests for slash commands at all.

**Comment by 01zulfi** [comment]
closing in favour of https://github.com/TheOdinProject/odin-bot-v2/pull/407

**Pull request closed without merging**
