### PR TITLE
Added CodePen and Repl links to /code

### PR DESCRIPTION
**Pull request by zainthedev**
- [x ] You have read the [Odin Bot README/Contributing Guide](https://github.com/TheOdinProject/odin-bot-v2/blob/master/README.md).

#### 1.Describe the changes made:

Added a line suggesting the use of CodePen and Repl.it for larger code snippets.

#### 3. If this PR is related to an open issue please reference it with the `#` operator and the issue number below:

#112

### CODE REVIEW

**Review by twalton83 — COMMENTED** [review]
Happy to merge once I get explanation of the package-lock.json.

**Comment by marvingay** [comment]
@twalton83 It's likely because there is a peer dependency that has a newer version (likely as a result of the semi-recent `axios` bump I pushed through).

Anyone who does a fresh npm install will likely end up with a modified package-lock.json

I can update it in a separate commit.

**Comment by twalton83** [comment]
@marvingay Noted, thanks!

**Comment by KevinMulhern** [comment]
Hey guys, I was looking at this yesterday because the same thing is happening in this PR: https://github.com/TheOdinProject/odin-bot-v2/pull/118/files 

It looks like a lot of stuff was removed from the package-lock file by accident here (the numbers add up): https://github.com/TheOdinProject/odin-bot-v2/commit/9b901da1d0d8cfc2d229c8cc9c8113be978d1a62

we should merge the package-lock changes back in with this or the other PR.

**Comment by marvingay** [comment]
Ah good catch, I flew by that. Cheers.

**Pull request merged**
