### PR TITLE
Update legacy !code command

### LINKED ISSUE #411: !code: update the !code command to same formatting as /code slash command
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

update the `!code` command to the exact same formatting as the `/code` command has. This includes descriptive links

**2. Acceptance Criteria:**

- [ ] update title to sentence case "How to share your code"
- [ ] copy the body / main text from the `/code` slash command
- [ ] update snapshots

**3. Additional Information:**

This is probably one of the old commands that will remain available as non-slash

### PR DESCRIPTION
**Pull request by ManonLef**
## Because

- The legacy `!code` command formatting should be in line with the updated `/code` command one

## This PR

- removes the legacy code command from the help.js file and gives it its own code.js file 
- updates the mention to be outside the embed so the user actually receives a ping with the bot output. For the future we could update this command to also ping while replying to a msg. 
- makes the output the same as the /code command output including descriptive links
- adds test and snapshot in their own file

## Issue

Closes #411

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update verbiage`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If this PR adds new features or functionality, I have added new tests
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date

### CODE REVIEW

**Comment by Asartea** [comment]
Looks great apart from the one linter complaint :rocket:

**Comment by ManonLef** [comment]
Thanks @Asartea didn't stay up for the tests apparently

**Review by zachmmeyer — APPROVED** [review]
Here we goooo

**Comment by Asartea** [comment]
Yeah, I think (by far) the majority of its uses are as a text command in a running sentence

**Comment by ManonLef** [comment]
@01zulfi yes. Sorry, I probably should have mentioned that here as well, not just on the issue 😊

**Pull request merged**
