### PR TITLE
Question command: Update verbiage

### PR DESCRIPTION
**Pull request by mgrigoriev8109**
Change description of the simpleCommands.js question! command, and update the associated test

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update verbiage`

Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date

<hr>

**1. Because:**
After a conversation regarding the possibility of changing the question command, the following prompt was accepted as a possible change. 

**2. This PR:**
Updates the question prompt and the associated test.

### CODE REVIEW

**Comment by I3uckwheat** [comment]
@mgrigoriev8109 Hey! can you please attach a screenshot of what this looks like in chat?

**Comment by mgrigoriev8109** [comment]
image
Sure thing @I3uckwheat, let's see if this works.

**Review by I3uckwheat — CHANGES_REQUESTED** [review]
The only thing I'd like to see changed is having a few pieces of that bolded to make it easier to read the labels:

**Lesson Link:**
**What I've Tried:**

**Comment by mgrigoriev8109** [comment]
Updated the command and associated test, this is what it currently looks like. 
image

**Review by I3uckwheat — APPROVED** [review]

**Pull request merged**
